#:schema node_modules/wrangler/config-schema.json
name = "scheduled-message"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
enabled = true